---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(v2\.[0-9]+\.[0-9]+-ls[0-9]+)$'
spec:
  releaseName: traefik-external
  helmVersion: v3
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 2.3.1
  values:
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik-external"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    logs:
      general:
        format: json
        level: ERROR
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.68.69.3
    ports:
      traefik:
        expose: true