apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "9.4.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    additionalArguments:
      - "--log.level=DEBUG"     
      #- "--metrics.prometheus=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--serversTransport.insecureSkipVerify=true" # for k8s dash
      - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entrypoints.fooudp.address=:8191/udp"
     # - "--providers.kubernetesingress.ingressclass=traefik-external"
     # - "--providers.kubernetescrd"

    service:
      spec:
        externalTrafficPolicy: Local # https://github.com/rancher/k3s/issues/1652 need this for X-Real-Ip?    

