apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "9.8.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    additionalArguments:
      - "--global.checknewversion"
      - "--global.sendanonymoususage"
      - "--entryPoints.traefik.address=:9000/tcp"
      - "--entryPoints.web.address=:8000/tcp"
      - "--entryPoints.websecure.address=:8443/tcp"
      - "--api.dashboard=true"
      - "--ping=true"
      #- "--providers.kubernetescrd"
      #- "--providers.kubernetesingress"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--serversTransport.insecureSkipVerify=true"  # for k8s dash
      - "--entryPoints.web.forwardedHeaders.insecure"
    service:
      spec:
        externalTrafficPolicy: Local # https://github.com/rancher/k3s/issues/1652 need this for X-Real-Ip?    
---
# dashboard.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.kube.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService