apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gotk-components.yaml
- ./gotk-sync.yaml
- ./helm-repos/democratic-csi.yaml
- ./helm-repos/halkeye.yaml
- ./helm-repos/helm-stable.yaml
- ./helm-repos/k8s-at-home.yaml
- ./helm-repos/kubernetes-dashboard.yaml
- ./helm-repos/portainer.yaml
- ./helm-repos/rimusz.yaml
- ./helm-repos/traefik.yaml
