apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "9.4.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    additionalArguments:
      - "--log.level=DEBUG"
      # - "--tracing.jaeger.samplingServerURL=http://monitoring-jaeger-agent.monitoring.svc.cluster.local:5778/sampling"
      # - "--tracing.jaeger.localAgentHostPort=monitoring-jaeger-agent.monitoring.svc.cluster.local:6831"
      # - "--tracing.jaeger.collector.endpoint=http://monitoring-jaeger-collector.monitoring.svc.cluster.local:14268/api/traces?format=jaeger.thrift"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--serversTransport.insecureSkipVerify=true" # for k8s dash
      - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entrypoints.fooudp.address=:8191/udp"